# Generated by Django 4.1.4 on 2023-01-05 05:42

from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("age", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=50, null=True)),
                #("phone", models.CharField(max_length=50, null=True)),
            ],
            options={
                "db_table": "t_users",
            },
        ),
    ]
